AllCops:
    NewCops: enable
    TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - valvat.gemspec
    - spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

Style/StringChars:
    Enabled: false
